<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="yangxiaobin" name="Default test" tests="2" failures="2" timestamp="15 Sep 2017 03:55:13 GMT" time="2.736" errors="0">
  <testcase name="test_image_rec" time="1.397" classname="cn.test.framework.tests.InterfaceTest">
    <failure type="java.lang.AssertionError" message=" 期望值: 北京市崇文区安化北里1号长保大厦123 实际值: 北京市崇文区安化北里1号笋保大厦">
      <![CDATA[java.lang.AssertionError:  期望值: 北京市崇文区安化北里1号长保大厦123 实际值: 北京市崇文区安化北里1号笋保大厦
	at org.testng.Assert.fail(Assert.java:83)
	at com.test.framework.utils.AssertUtil.verifyFail(AssertUtil.java:36)
	at cn.test.framework.tests.InterfaceTest.test_image_rec(InterfaceTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError:  期望值: 北京市崇文区安化北里1号长保大厦123 实际值: 北京市崇文区安化北里1号笋保大厦
	at org.testng.Assert.fail(Assert.java:94)
	at com.test.framework.utils.AssertUtil.verifyFail(AssertUtil.java:33)
	... 25 more
]]>
    </failure>
  </testcase> <!-- test_image_rec -->
  <testcase name="test_image_rec" time="1.043" classname="cn.test.framework.tests.InterfaceTest">
    <failure type="java.lang.AssertionError" message=" 期望值: 北京市崇文区安化北里1号长保大厦 实际值: 北京市崇文区安化北里1号笋保大厦">
      <![CDATA[java.lang.AssertionError:  期望值: 北京市崇文区安化北里1号长保大厦 实际值: 北京市崇文区安化北里1号笋保大厦
	at org.testng.Assert.fail(Assert.java:83)
	at com.test.framework.utils.AssertUtil.verifyFail(AssertUtil.java:36)
	at cn.test.framework.tests.InterfaceTest.test_image_rec(InterfaceTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError:  期望值: 北京市崇文区安化北里1号长保大厦 实际值: 北京市崇文区安化北里1号笋保大厦
	at org.testng.Assert.fail(Assert.java:94)
	at com.test.framework.utils.AssertUtil.verifyFail(AssertUtil.java:33)
	... 25 more
]]>
    </failure>
  </testcase> <!-- test_image_rec -->
</testsuite> <!-- Default test -->
